In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("Bookings.csv")

In [5]:
print(df)

                       Date      Time     Booking_ID        Booking_Status  \
0       2024-07-26 14:00:00  14:00:00  CNR7153255142    Canceled by Driver
1       2024-07-25 22:20:00  22:20:00  CNR2940424040               Success
2       2024-07-30 19:59:00  19:59:00  CNR2982357879               Success
3        2024-07-22 3:15:00  03:15:00  CNR2395710036  Canceled by Customer
4        2024-07-02 9:02:00  09:02:00  CNR1797421769               Success
...                     ...       ...            ...                   ...
103019   2024-07-31 9:06:00  09:06:00  CNR9488489435               Success
103020  2024-07-31 15:12:00  15:12:00  CNR3151743100               Success
103021  2024-07-31 13:59:00  13:59:00  CNR1286151233               Success
103022  2024-07-31 14:56:00  14:56:00  CNR2027162035               Success
103023  2024-07-31 13:57:00  13:57:00  CNR9770709721               Success

       Customer_ID Vehicle_Type    Pickup_Location  Drop_Location  V_TAT  \
0        CID713523  Prime Sedan        Tumkur Road       RT Nagar    NaN
1        CID225428         Bike        Magadi Road        Varthur  203.0
2        CID270156    Prime SUV      Sahakar Nagar        Varthur  238.0
3        CID581320        eBike         HSR Layout    Vijayanagar    NaN
4        CID939555         Mini        Rajajinagar    Chamarajpet  252.0
...            ...          ...                ...            ...    ...
103019   CID371654   Prime Plus      Richmond Town        Varthur  245.0
103020   CID334158         Auto        Vijayanagar  Richmond Town   84.0
103021   CID113188    Prime SUV  Bannerghatta Road       JP Nagar   35.0
103022   CID118301        eBike        Indiranagar    Magadi Road  210.0
103023   CID217959         Auto             Ulsoor         Hennur  175.0

        C_TAT  ...      Canceled_Rides_by_Driver Incomplete_Rides  \
0         NaN  ...  Personal & Car related issue              NaN
1        30.0  ...                           NaN               No
2       130.0  ...                           NaN               No
3         NaN  ...                           NaN              NaN
4        80.0  ...                           NaN               No
...       ...  ...                           ...              ...
103019   35.0  ...                           NaN               No
103020  145.0  ...                           NaN               No
103021   75.0  ...                           NaN               No
103022  140.0  ...                           NaN               No
103023  125.0  ...                           NaN               No

       Incomplete_Rides_Reason Booking_Value  Payment_Method Ride_Distance  \
0                          NaN           444             NaN             0
1                          NaN           158            Cash            13
2                          NaN           386             UPI            40
3                          NaN           384             NaN             0
4                          NaN           822     Credit Card            45
...                        ...           ...             ...           ...
103019                     NaN           111            Cash            41
103020                     NaN          1097             UPI            17
103021                     NaN          2201            Cash            37
103022                     NaN           267             UPI            47
103023                     NaN           462             UPI             3

        Driver_Ratings  Customer_Rating  Vehicle Images Unnamed: 20
0                  NaN              NaN          #NAME?         NaN
1                  4.1              4.0          #NAME?         NaN
2                  4.2              4.8          #NAME?         NaN
3                  NaN              NaN          #NAME?         NaN
4                  4.0              3.0          #NAME?         NaN
...                ...              ...             ...         ...
103019             3.6              3.8          #NAME?         NaN
103020             4.3              3.3          #NAME?         NaN
103021             3.6              3.2          #NAME?         NaN
103022             3.4              3.1          #NAME?         NaN
103023             4.8              4.4          #NAME?         NaN

[103024 rows x 21 columns]

In [15]:
print(df.columns.tolist())

['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT', 'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver', 'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value', 'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating', 'Vehicle Images', 'Unnamed: 20']

In [9]:
successful_bookings = df[df['Booking_Status'] == 'Success']
successful_bookings.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN
5,2024-07-13 4:42:00,04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,...,NaN,No,NaN,173,UPI,41,3.4,4.6,#NAME?,NaN
6,2024-07-23 9:51:00,09:51:00,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,...,NaN,No,NaN,140,Cash,49,3.2,4.5,#NAME?,NaN

1. Retrieve all successful bookings

In [10]:
customer_cancelled = df[df['Booking_Status'] == 'Canceled by Customer']

print("Total Cancelled Rides:", customer_cancelled.shape[0])

Total Cancelled Rides: 10499

2. Find the average ride distance for each vehicle type

In [11]:
df.groupby('Vehicle_Type')['Ride_Distance'].mean().reset_index()

  Vehicle_Type  Ride_Distance
0         Auto       6.238089
1         Bike      15.533079
2         Mini      15.510102
3   Prime Plus      15.447474
4    Prime SUV      15.274514
5  Prime Sedan      15.764939
6        eBike      15.580589

4. List the top 5 customers who booked the highest number of rides

In [12]:
top_5_customers = (
    df.groupby('Customer_ID')
      .size()
      .reset_index(name='Total_Rides')
      .sort_values(by='Total_Rides', ascending=False)
      .head(5)
)

top_5_customers

      Customer_ID  Total_Rides
89695   CID954071            5
17605   CID268274            4
17111   CID263459            4
9388    CID189965            4
30150   CID387617            4

5. Number of rides cancelled by drivers due to personal and car-related issues

In [16]:
driver_cancelled = (
    df['Canceled_Rides_by_Driver']
    == 'Personal & Car related issue'
).sum()

print("Total Rides:", driver_cancelled)

Total Rides: 6542

6. Find the maximum and minimum driver ratings for Prime Sedan bookings

In [17]:
prime_sedan = df[df['Vehicle_Type'] == 'Prime Sedan']

max_rating = prime_sedan['Driver_Ratings'].max()
min_rating = prime_sedan['Driver_Ratings'].min()

print("Maximum Driver Rating:", max_rating)
print("Minimum Driver Rating:", min_rating)

Maximum Driver Rating: 5.0
Minimum Driver Rating: 3.0

7. Retrieve all rides where payment was made using UPI

In [18]:
upi_rides = df[df['Payment_Method'] == 'UPI']

upi_rides.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
5,2024-07-13 4:42:00,04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,...,NaN,No,NaN,173,UPI,41,3.4,4.6,#NAME?,NaN
12,2024-07-27 13:18:00,13:18:00,CNR4524472111,Success,CID540929,Auto,Cox Town,Yelahanka,126.0,35.0,...,NaN,No,NaN,330,UPI,8,3.0,4.8,#NAME?,NaN
14,2024-07-16 9:54:00,09:54:00,CNR8181602032,Success,CID167642,Bike,Indiranagar,MG Road,70.0,95.0,...,NaN,No,NaN,378,UPI,18,4.8,4.1,#NAME?,NaN
15,2024-07-02 10:25:00,10:25:00,CNR8090918544,Success,CID640151,Bike,Magadi Road,HSR Layout,126.0,95.0,...,NaN,No,NaN,343,UPI,23,3.7,3.6,#NAME?,NaN

8. Find the average customer rating per vehicle type

In [19]:
avg_customer_rating = (
    df.groupby('Vehicle_Type')['Customer_Rating']
      .mean()
      .reset_index()
)

avg_customer_rating

  Vehicle_Type  Customer_Rating
0         Auto         3.998811
1         Bike         3.993376
2         Mini         3.997731
3   Prime Plus         4.009499
4    Prime SUV         3.999378
5  Prime Sedan         4.001589
6        eBike         3.987854

9. Calculate the total booking value of rides completed successfully

In [20]:
total_booking_value = (
    df[df['Booking_Status'] == 'Success']
    ['Booking_Value']
    .sum()
)

print("Total Booking Value:", total_booking_value)

Total Booking Value: 35080467

10. List all incomplete rides along with the reason

In [21]:
incomplete_rides = df[
    df['Incomplete_Rides'] == 'Yes'
][['Booking_ID',
   'Incomplete_Rides',
   'Incomplete_Rides_Reason']]

incomplete_rides

           Booking_ID Incomplete_Rides Incomplete_Rides_Reason
38      CNR5176704322              Yes         Customer Demand
49      CNR9312632867              Yes       Vehicle Breakdown
70      CNR7924302885              Yes         Customer Demand
93      CNR1640228587              Yes             Other Issue
101     CNR7623690602              Yes             Other Issue
...               ...              ...                     ...
102859  CNR5546265534              Yes         Customer Demand
102870  CNR1954831907              Yes       Vehicle Breakdown
102973  CNR1271821250              Yes       Vehicle Breakdown
102978  CNR4652634649              Yes       Vehicle Breakdown
103011  CNR5427755403              Yes             Other Issue

[3926 rows x 3 columns]